# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  Build:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [19.x]
    steps:
        - name: Build
          uses: actions/checkout@v3
          with:
            clean: 'false'
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        
  DeployStaging:
    name: Deploy to Staging 
    if: github.event.ref == 'refs/heads/master'
    needs: [Build]
    runs-on: self-hosted
    environment: 
      name: Staging
    steps:
      - name: Deploy            
        run: node -v
      - name: 'Create env file'
        run: |
          touch .env
          echo DB_TOKEN=${{ secrets.DB_TOKEN }} >> .env
          cat .env
  
  DeployProduction:
    name: Deploy to Production 
    needs: [DeployStaging]
    runs-on: self-hosted
    environment: 
      name: Production
      url: 'http://130.162.57.32:8080'
    steps:
     - name: Use Node.js ${{ matrix.node-version }}
       uses: actions/setup-node@v3     
     - run: npm i
     - run: npm run build --if-present 
     - run: npx pm2 restart SimonBOT
